#!/usr/bin/python
# -*- coding: utf-8 -*-

SITE_PACKAGES = '/home/vbraun/Code/blas-config/local/lib/python2.7/site-packages'
PKG_CONFIG_PATH = '/home/vbraun/Code/blas-config/local/lib/pkgconfig'

import logging
logging.basicConfig()
log = logging.getLogger()



import sys
sys.path.insert(1, SITE_PACKAGES)

from blas_config.cmdline import launch
launch()






